<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="4" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-02-17T18:45:47Z" name="Default suite" finished-at="2022-02-17T18:46:09Z" duration-ms="21395">
    <groups>
    </groups>
    <test started-at="2022-02-17T18:45:47Z" name="Default test" finished-at="2022-02-17T18:46:09Z" duration-ms="21395">
      <class name="com.wiki.tests.FunctionalTests">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.wiki.tests.FunctionalTests@4f6f416f]" started-at="2022-02-17T18:45:47Z" name="setUp" finished-at="2022-02-17T18:45:51Z" duration-ms="3879" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyPageTitle()[pri:0, instance:com.wiki.tests.FunctionalTests@4f6f416f]" started-at="2022-02-17T18:45:51Z" name="verifyPageTitle" finished-at="2022-02-17T18:45:51Z" duration-ms="34" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyPageTitle -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.wiki.tests.FunctionalTests@4f6f416f]" started-at="2022-02-17T18:45:51Z" name="tearDown" finished-at="2022-02-17T18:45:51Z" duration-ms="157" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.wiki.tests.FunctionalTests@4f6f416f]" started-at="2022-02-17T18:45:51Z" name="setUp" finished-at="2022-02-17T18:45:53Z" duration-ms="2132" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginWithInvalidCredentials()[pri:1, instance:com.wiki.tests.FunctionalTests@4f6f416f]" started-at="2022-02-17T18:45:53Z" name="loginWithInvalidCredentials" finished-at="2022-02-17T18:45:55Z" duration-ms="1789" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.wiki.tests.FunctionalTests.loginWithInvalidCredentials(FunctionalTests.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithInvalidCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.wiki.tests.FunctionalTests@4f6f416f]" started-at="2022-02-17T18:45:55Z" name="tearDown" finished-at="2022-02-17T18:45:55Z" duration-ms="179" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.wiki.tests.FunctionalTests@4f6f416f]" started-at="2022-02-17T18:45:55Z" name="setUp" finished-at="2022-02-17T18:45:58Z" duration-ms="2173" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validLogin()[pri:2, instance:com.wiki.tests.FunctionalTests@4f6f416f]" started-at="2022-02-17T18:45:58Z" name="validLogin" finished-at="2022-02-17T18:45:58Z" duration-ms="721" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.wiki.tests.FunctionalTests@4f6f416f]" started-at="2022-02-17T18:45:58Z" name="tearDown" finished-at="2022-02-17T18:45:59Z" duration-ms="177" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.wiki.tests.FunctionalTests@4f6f416f]" started-at="2022-02-17T18:45:59Z" name="setUp" finished-at="2022-02-17T18:46:01Z" duration-ms="2124" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyFooterLinks()[pri:3, instance:com.wiki.tests.FunctionalTests@4f6f416f]" started-at="2022-02-17T18:46:01Z" name="verifyFooterLinks" finished-at="2022-02-17T18:46:01Z" duration-ms="406" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyFooterLinks -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.wiki.tests.FunctionalTests@4f6f416f]" started-at="2022-02-17T18:46:01Z" name="tearDown" finished-at="2022-02-17T18:46:01Z" duration-ms="162" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.wiki.tests.FunctionalTests@4f6f416f]" started-at="2022-02-17T18:46:01Z" name="setUp" finished-at="2022-02-17T18:46:03Z" duration-ms="2195" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifySearch()[pri:4, instance:com.wiki.tests.FunctionalTests@4f6f416f]" started-at="2022-02-17T18:46:03Z" name="verifySearch" finished-at="2022-02-17T18:46:05Z" duration-ms="1427" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySearch -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.wiki.tests.FunctionalTests@4f6f416f]" started-at="2022-02-17T18:46:05Z" name="tearDown" finished-at="2022-02-17T18:46:05Z" duration-ms="182" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.wiki.tests.FunctionalTests@4f6f416f]" started-at="2022-02-17T18:46:05Z" name="setUp" finished-at="2022-02-17T18:46:07Z" duration-ms="2122" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="invalidSearch()[pri:5, instance:com.wiki.tests.FunctionalTests@4f6f416f]" started-at="2022-02-17T18:46:07Z" name="invalidSearch" finished-at="2022-02-17T18:46:08Z" duration-ms="1333" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.wiki.pages.HomePage.search(HomePage.java:174)
at com.wiki.tests.FunctionalTests.invalidSearch(FunctionalTests.java:79)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidSearch -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.wiki.tests.FunctionalTests@4f6f416f]" started-at="2022-02-17T18:46:08Z" name="tearDown" finished-at="2022-02-17T18:46:09Z" duration-ms="162" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.wiki.tests.FunctionalTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
